! Define the subroutines that get the reference data and the data generated by the potential
module datafunc
	use globals

	public		:: inirefdata,getpotdata,checkdata,savebestpotdata

contains
	! Get the data from the reference dataset file
	subroutine inirefdata
		implicit none

		integer			:: i

		open(11,file='refdata.dat',status='old',err=187)

		goto 188

187		stop 'INIREFDATA: File refdata.dat not found!'

188		read(11,*) ndata

		allocate(refdata(ndata))
		allocate(weight(ndata))
		allocate(tolerance(ndata))
		allocate(qualiweight(ndata))
		allocate(potdata(ndata))
		allocate(bestpotdata(ndata))

		do i=1,ndata
			read(11,*) refdata(i),weight(i),tolerance(i),qualiweight(i)
		enddo

		if(normweight) weight=weight/maxval(weight)

		close(11)
	end subroutine

	! Get the data generated by the trial potential that will be compared to the reference data
	function getpotdata()
		implicit none

		integer		:: i
		integer		:: getpotdata

		getpotdata=0

		open(12,file='potdata.dat',status='old',err=195)

		goto 196

195		stop 'GETPOTDATA: File potdata.dat not found!'

196		do i=1,ndata
			read(12,*) potdata(i)

			if(isnan(potdata(i)))then
				getpotdata=-1

				exit
			end if
		end do

		close(12)

		return		
	end function

	! Perform a last check for qualitative agreement between the reference data and the potential data
	subroutine checkdata
		implicit none

		integer		:: i

		do i=1,ndata		
			if(abs(refdata(i))>0.0d0.and.qualiweight(i))then
				if(potdata(i)/refdata(i)<0.0d0)then
					if(abs(tolerance(i))>EPSILON)then
						zeta=zeta+fzeta((potdata(i)/refdata(i)),0.0d0)
					else
						zeta=zeta+fzeta(potdata(i),0.0d0)
					end if
				end if
			end if
		end do
	end subroutine

	! Save information on the best potential data so far
	subroutine savebestpotdata
		implicit none

		integer			:: i
		character*8,parameter	:: fmt1='(4F20.6)'
	
		open(161,file='bestpotdata.dat')
		rewind(161)

		write(161,'(A)') '# Reference     Calculated     Difference (absolute)'
		write(161,'(A)') '# --------------------------------------------------'
		write(161,*)

		do i=1,ndata
			write(161,FMT1) refdata(i),potdata(i),abs(refdata(i)-potdata(i))
		end do

		close(161)
	end subroutine
end module
